# image: node:latest
#
# before_script:
# - npm install
# - npm install -g typescript
#
# build:
#   script:
#   - npm run build

image: docker:latest

variables:
      dockerTag: '$CI_BUILD_REF'
      CONTAINER_IMAGE: threebx/threshodl/threshodl-wallet-server:latest

services:
      - docker:dind

before_script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
      #- echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
      #- echo "$ACCOUNT_PASSWORD" | docker login -u $ACCOUNT_USERNAME --password-stdin registry.gitlab.com

stages:
- build

build:
      stage: build
      script:
            - docker build -t $CONTAINER_IMAGE .
            - docker push $CONTAINER_IMAGE
