# image: node:latest
#
# before_script:
# - npm install
# - npm install -g typescript
#
# build:
#   script:
#   - npm run build

image: docker:latest

variables:
      dockerTag: '$CI_BUILD_REF'
      CONTAINER_IMAGE: threebx/threshodl/threshodl-wallet-server:1

services:
      - docker:dind

before_script:
      - echo "$ACCOUNT_PASSWORD" | docker login -u $ACCOUNT_USERNAME --password-stdin registry.gitlab.com

stages:
- build

build:
      stage: build
      script:
            - docker build -t $CONTAINER_IMAGE .
            - docker push registry.gitlab.com/$CONTAINER_IMAGE
